name: My First Manual Workflow
on: [workflow_dispatch]
jobs:
  example:
    name: Example Job
    runs-on: macos-12
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: ...
        run: ...
